# Generated by Django 3.1.7 on 2023-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.EmailField(default='yx@seller.com', max_length=254),
            preserve_default=False,
        ),
    ]
