version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python3 manage.py runserver
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 store-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
