version: 2.1

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python3 store/tests/test_login.py
