os: windows # => 1
language: python # => 2
python: # => 3
  - "3.6"
  - "3.7"
  - "3.8"
jobs: # => 4
jobs:
  say-hello:
   
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
env: # => 5
  -DJANGO=4.1.7 DB=sqlite
install: #=> 6
  - python -m pip install requirements.txt
script: # => 7
  - python manage.py runserver
